bitleak/lmstfy

engine/redis/info.go
engine/redis/metrics.go

MOD: export redis maxmemory metrics

---

client/client.go
client/client_test.go
server/handlers/queue.go
server/handlers/queue_test.go
server/route.go

MOD: add republish, ack and publish job atomic

---

client/client.go

Fix bug of closing the ioreader of response body too early

---

config/config.go
config/config_test.go
config/demo-conf.toml
helper/redis.go

MOD: add redis db config

---

engine/engine.go
engine/migration/engine.go
engine/redis/engine.go
engine/redis/meta.go
server/handlers/admin.go

MOD: print some logs while initialize meta and setup error

---

README.md
doc/administration.cn.md
doc/administration.en.md

MOD: add grafana dashboard link

---

engine/engine.go
engine/job.go
engine/migration/engine.go
engine/redis/engine.go
engine/redis/queue.go
go.mod
go.sum
push/manager.go
push/meta.go
push/meta_test.go
push/pusher.go
push/pusher_test.go
push/setup_test.go
server/handlers/middleware.go
server/handlers/pusher.go
server/handlers/pusher_test.go
server/handlers/setup_test.go
server/main.go

1.  catch the panic in the async goroutine
2. check the pool and namespace before register the pusher

WIP:  supports the push mode when consuming the queue

---

engine/engine.go
push/manager.go
push/meta.go
push/pusher.go
push/setup_test.go
server/main.go
server/middleware/middleware.go
throttler/throttler.go

* shutdown the engine and close the Redis
* shutdown the throttler and close the Redis
* shutdown the meta manager and close the Redis

FIX: explictly shutdown the submodule after receving the terminate signal

---

config/config.go
config/demo-conf.toml
server/main.go

ADD: add basic auth for Admin API

---

engine/redis/hooks/init.go
engine/redis/hooks/metrics.go
helper/redis.go

ADD: key metrics for the redis client

---

engine/engine.go
engine/migration/setup.go
engine/migration/setup_test.go
engine/pool.go
engine/redis/setup.go
server/handlers/admin.go
server/handlers/queue_test.go
server/handlers/sentinel_test.go

* Move engine pool function to a single file
* Refactor engine kind from var string to const

Refactor engine pool and use const instead of string var

---

engine/pool.go
engine/redis/constant.go
engine/redis/deadletter.go
engine/redis/queue.go
engine/redis/timer.go

* refactor redis sha variable from underscore to camelcase
* refactor engine pool register function

Refactor redis engine code

---

server/handlers/metrics.go
server/main.go
server/route.go

Add metric for auth failure requests

---

server/handlers/throttler.go
server/handlers/throttler_test.go
server/main.go
server/route.go

* move admin router code to SetupAdminRouter func
* remove useless throttler handler input param
* use const in throttler handler action

Refactor server code

---

engine/engine.go
engine/migration/engine.go
engine/redis/engine.go
engine/redis/engine_test.go
engine/redis/queue.go
server/handlers/queue.go
server/handlers/queue_test.go

Didn't refactor the client code, freeze_tries may be in use by some people.

Remove freeze tries from engine interface

---

engine/redis-v2/constant.go
engine/redis-v2/queue_manager.go
engine/redis-v2/timer_manager.go
engine/redis-v2/timer_manager_test.go
engine/redis-v2/utils.go
go.mod
go.sum

V2 feature/timer manager

---

engine/redis-v2/deadletter.go
engine/redis-v2/deadletter_test.go
engine/redis-v2/pool.go
engine/redis-v2/pool_test.go
engine/redis-v2/setup_test.go

* copy deadletter and pool code from v1 engine
* refactor deadletter and pool code suit with v2 engine
* remove metrics collect temporary

V2 feature/deadletter and pool

---

engine/redis-v2/deadletter.go
engine/redis-v2/deadletter_test.go
engine/redis-v2/pool.go
engine/redis-v2/queue.go
engine/redis-v2/queue_manager.go
engine/redis-v2/queue_test.go

* copy queue from redis v1 engine
* refactor queue code to support v2 engine
* refactor deadletter use struct queue
queue need not contain timer, so poped job should be added in engine code. Will be implemented in next pr

V2 feature/add queue

---

engine/redis-v2/deadletter.go
engine/redis-v2/hooks/init.go
engine/redis-v2/hooks/metrics.go
engine/redis-v2/info.go
engine/redis-v2/info_test.go
engine/redis-v2/metrics.go
engine/redis-v2/pool.go
engine/redis-v2/queue.go
engine/redis-v2/timer_manager.go

* copy info from v1 to v2
* copy metrics from v1 to v2
* refactor info and metrics to v2
Some metrics maybe not suitable in v2, I just refactor timer_size to support v2. We can review v2 metrics in the future.

V2 feature/metrics and info

---

engine/redis-v2/engine.go
engine/redis-v2/engine_test.go
engine/redis-v2/pool.go

* copy engine from v1
* refactor engine to support v2
* fix engine testcase
todo: only check queue exist in publish, because I didn't have a good idea to check this currently.
note: maybe do tries-- in pool.Get and we need another function pool.Peek, or do this in lua script?

V2 feature/engine

---

scripts/run-test.sh
throttler/throttler.go

- Fix race condition when testing with -race flag
- Update Limiter validate logic and error message
- Improve `throttler` package comment grammar

Fix race condition when testing with -race flag

---

build.sh

Update arm TARGET_ARCH value in order to meet the GOOS and GOARCH pair compatibility.

Update target architecture in build.sh

---

engine/redis_v2/engine.go
engine/redis_v2/engine_test.go
storage/manager.go
storage/persistence/spanner/spanner.go
storage/persistence/spanner/spanner_test.go
storage/persitence.go

add job peek from storage

---

engine/redis_v2/engine_test.go
engine/redis_v2/timer_test.go
go.mod
log/utils.go
server/main.go
storage/manager.go
storage/persistence/spanner/spanner.go
storage/persitence.go
storage/pumper/pumper.go
storage/pumper/pumper_test.go

Add more logs for storage

---

engine/redis_v2/engine.go
storage/manager.go
storage/metrics.go

1. add storage add job and delete jobmeterics.
2. fix format

Add monitor meterics for secondary storage

---

engine/redis_v2/engine_test.go
storage/manager.go

Add redis memory usage metrics when storage pumping data

---

helper/redis.go
helper/redis_test.go

1. add checking for redis maxmemory, it must be greater than zero when secondary storage is enabled.
2. add relevant unit tests.

Add redis config maxmemory validation and relevant test

---

storage/pumper/pumper.go

Fix pumper lock issue so that it can continue pumping after reacquiring the lock.

Fix pumper lock issue 

---

docker/docker-compose.yml

Sync redis conf in docker/docker-compose.yml
